name: Scheduled Backend Job

on:
  schedule:
    - cron: "*/7 * * * *"
  workflow_dispatch:

jobs:
  call-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger backend cron endpoint
        run: |
          curl -X GET https://hackulus25-be-express.onrender.com/db-job
